<section class="container">
    <h2>Bienvenue à l'agence du coin !</h2>

    <!--Carousel-->
    <article>
        <div class="carousel">
            <div class="carousel__item carousel__item--visible">
                <img src="public/images/appartDemo1.jpg" alt="image d'appartement 1" />
            </div>
            <div class="carousel__item">
                <img src="public/images/appartDemo2.jpg" alt="image d'appartement 2" />
            </div>
            <div class="carousel__item">
                <img src="public/images/appartDemo3.jpg" alt="image d'appartement 3" />
            </div>
            <div class="carousel__actions">
                <button id="carousel__button--prev" aria-label="Previous slide">
                    <i class="fa-solid fa-arrow-left-long"></i>
                </button>
                <button id="carousel__button--next" aria-label="Next slide">
                    <i class="fa-solid fa-arrow-right"></i>
                </button>
            </div>
        </div>
        <p>
            Présents sur le secteur de Nantes depuis 1980 l'agence du coin est un acteur majeur dans le monde de l'immobilier local. Fier de son héritage familial nous souhaitons rester une entreprise à taille humaine privilégiant ainsi la qualité à la quantité. Si vous souhaitez acheter ou vendre alors ne cherchez pas plus loin, vous trouverez votre bonheur à l'agence du coin !
        </p>
    </article>

    <!--Présentation-->

    <article class="article__presentation">
        <h3>Nos Valeurs</h3>
        <p>
            L'agence du coin est avant tout votre partenaire pour chacun de vos projets immobiliers. Nous nous proposons de vous accompagner de la recherche de votre futur chez vous jusqu'à la signature de l'acte authentique chez le notaire. Transparents et disponibles pour vous nos agents seront à vos côtés à tout instant !
        </p>
        <div class="article__presentation--image">
            <img src="public/images/logo.jpg" alt="logo maison miniature" class="img__presentation" />
            <img src="public/images/clefs.jpg" alt="logo clef porte maison" class="img__presentation" />
        </div>
    </article>

    <article class="article__presentation">
        <h3>Apporteur d'affaires, pourquoi pas vous ? </h3>
        <p>
            Soucieux de toujours apporter les meilleurs offres du marché immobilier à nos futurs acheteurs nous sommes constamment à l'affût de nouveaux biens à leur faire découvrir. Si vous connaissez dans votre entourage des personnes ayant un projet de vente alors n'hésitez pas à nous le faire savoir ! Cela peut vous rapporter très gros !
        </p>
        <div class="article__presentation--image">
            <img src="public/images/business.jpg" alt="logo business" class="img__presentation2" />
        </div>
    </article>

</section>