<!-- Notre équipe -->

<section class="card__container">

    <article class="card">
        <h4>Serge</h4>
        <img src="public/images/Serge.jpg" alt="image directeur Serge" />
        <p><i class="fa-solid fa-house"></i> Directeur d'agence</p>
        <hr class="line" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae
            sit beatae quis temporibus repellat quasi omnis consequatur!
            Doloribus, tempora quidem.
        </p>
        <hr class="line" />
        <button class="card__button">07 06 06 06 06</button>
    </article>

    <article class="card">
        <h4>Andrea</h4>
        <img src="public/images/Andrea.jpg" alt="image conseiller Andrea" />
        <p>
            <i class="fa-solid fa-house" id="card__stars"></i>Conseiller en
            vente
        </p>
        <hr class="line" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae
            sit beatae quis temporibus repellat quasi omnis consequatur!
            Doloribus, tempora quidem.
        </p>
        <hr class="line" />
        <button class="card__button">06 06 06 06 06</button>
    </article>

    <article class="card">
        <h4>Daniel</h4>
        <img src="public/images/Daniel.jpg" alt="image conseiller Daniel" />
        <p>
            <i class="fa-solid fa-house" id="card__stars2"></i>Conseiller en
            vente
        </p>
        <hr class="line" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae
            sit beatae quis temporibus repellat quasi omnis consequatur!
            Doloribus, tempora quidem.
        </p>
        <hr class="line" />
        <button class="card__button">06 06 06 06 06</button>
    </article>

    <article class="card">
        <h4>Julie</h4>
        <img src="public/images/Julie.jpg" alt="image secrétaire de direction Julie" />
        <p>
            <i class="fa-solid fa-phone" id="card__phone"></i>Secrétariat
        </p>
        <hr class="line" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae
            sit beatae quis temporibus repellat quasi omnis consequatur!
            Doloribus, tempora quidem.
        </p>
        <hr class="line" />
        <button class="card__button">02 02 02 02 02</button>
    </article>
</section>