<?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
    <h1>Modification d'un article</h1>
    <form method="POST" enctype="multipart/form-data" action="index.php?route=submitFormArticle&id=<?= htmlspecialchars($_GET['id']) ?>" class="formulaire">

    <?php else : ?>
        <h1>Ajout d'un article !</h1>
        <form method="POST" enctype="multipart/form-data" action="index.php?route=submitFormArticle" class="formulaire">
        <?php endif; ?>



            <legend>Merci de renseigner les information suivantes :</legend>
    
            <?php require_once('_errors.phtml'); ?>
            <?php require_once('_valids.phtml'); ?>
    
    
            <label for="titre">Titre :</label>
            <input type="text" name="titre" id="titre" value="<?= htmlspecialchars($addNewArticle['addTitre']) ?>">
    
            <label for="contenu">Contenu :</label>
            <textarea id="contenu" name="contenu" rows="5" cols="33"><?= htmlspecialchars($addNewArticle['addContenu']) ?></textarea>
    
    
            <?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
                <input type="submit" value="Modifier" class="input-color" />
            <?php else : ?>
                <input type="submit" value="Valider" class="input-color" />
            <?php endif; ?>

        </form>

        <button type="button" class="btn btn-warning"><a href=" index.php?route=accueilArticles">Retour</a></button>