<?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
    <h1>Modification d'un utilisateur</h1>
    <form method="POST" enctype="multipart/form-data" action="index.php?route=submitFormUser&id=<?= htmlspecialchars($_GET['id']) ?>" class="formulaire">

    <?php else : ?>
        <h1>Ajout d'un utilisateur !</h1>
        <form method="POST" enctype="multipart/form-data" action="index.php?route=submitFormUser" class="formulaire">
        <?php endif; ?>

            <legend>Merci de renseigner les information suivantes :</legend>
        
            <?php require_once('_errors.phtml'); ?>
            <?php require_once('_valids.phtml'); ?>
        
        
            <label for="nom">Nom :</label>
            <input type="text" name="nom" id="nom" value="<?= htmlspecialchars($addNewUser['addName']) ?>">
        
        
            <label for="prenom">Prenom :</label>
            <input type="text" name="prenom" id="prenom" value="<?= htmlspecialchars($addNewUser['addFirstName']) ?>">
        
        
            <label for="login">Login :</label>
            <input type="text" name="login" id="login" value="<?= htmlspecialchars($addNewUser['addLogin']) ?>">
        
        
            <label for="email">Email :</label>
            <input type="email" name="email" id="email" value="<?= htmlspecialchars($addNewUser['addEmail']) ?>">
        
            <label for="pass">Pass :</label>
            <input type="password" name="pass" id="pass" value="<?= htmlspecialchars($addNewUser['addPass']) ?>">
        
        
            <?php if (array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
                <input type="submit" value="Modifier" class="input-color" />
            <?php else : ?>
                <input type="submit" value="Valider" class="input-color" />
            <?php endif; ?>

        </form>

        <button type="button" class="btn btn-warning"><a href=" index.php?route=user">Retour</a></button>