<section class="container admin">
    <article class="row">
        <h1><strong>Liste des articles </strong><a href="index.php?route=displayFormArticle" class="btn btn-success btn-lg"> Ajouter</a></h1>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Titre</th>
                    <th>Contenu</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                <?php foreach ($articles as $article) : ?>
                    <tr>
                        <td><?= htmlspecialchars($article['id']) ?></td>
                        <td><?= htmlspecialchars($article['titre']) ?></td>
                        <td><?= htmlspecialchars($article['contenu']) ?></td>
                        <td id="btn-articles">
                            <a class="btn btn-secondary" href="index.php?route=seeArticle&id=<?= htmlspecialchars($article['id']) ?>"> Voir</a>
                            <a class="btn btn-primary" href="index.php?route=updateArticle&id=<?= htmlspecialchars($article['id']) ?>"> Modifier</a>
                            <form action="index.php?route=deleteArticle&id=<?= htmlspecialchars($article['id']) ?>" method="POST">
                                <input type="submit" value="supprimer" class="btn btn-danger">
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </article>
</section>

<section class="container admin">
    <article>
        <button type="button" class="btn btn-warning"><a href="index.php?route=accueil">Retour</a></button>
    </article>
</section>