<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8" />
    <title>L'agence du coin - BO </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Athiti&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Athiti&family=Merienda&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Zen+Maru+Gothic&display=swap" rel="stylesheet" />
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/0ff3ab6b3d.js" crossorigin="anonymous"></script>
    <!-- BootStrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!--Fichier CSS-->
    <link rel="stylesheet" href="../public/CSS/style.css" type="text/css" />
</head>

<body class="switch">
    <header>
        <section class="headband__top">
            <div class="container container__top">
                <article>
                    <ul class="menu__list">
                        <li class="menu__item menu__item--title">Cet espace est réservé aux membres de l'agence du coin. Pour toute demande contacter votre Admin !</li>
                    </ul>
                </article>
            </div>
        </section>

        <section class="container container__header">
            <article class="article__logo">
                <a href="../index.php">
                    <img src="../public/images/logo2.png" alt="logo agence" class="image__logo" />
                </a>
                <h1>L'AGENCE DU COIN</h1>
            </article>

            <!-- Statut de connexion ou de déconnexion -->
            <article class="article__connexion">
                <div>
                    <?php if (isset($_SESSION['connected']) && $_SESSION['connected'] == true) : ?>
                        <p><a href="index.php?route=disconnect">Déconnexion</a></p>
                    <?php else : ?>
                        <p><a href="index.php?route=home">Connexion</a></p>
                    <?php endif; ?>
                </div>
            </article>
        </section>

        <nav class="nav">
            <div class="container container__menu">
                <ul class="nav__list">
                    <li class="nav__list--message">Bienvenue sur l'espace administartion de l'agence du coin. </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Message qui permet d'afficher le nom et le prénom de l'utilisateur -->
    <?php if (isset($_SESSION['connected']) && $_SESSION['connected'] == true) : ?>
        <div class="container">
            <h5>Bonjour <?= $_SESSION['user']['nom'] . ' ' . $_SESSION['user']['prenom'] ?></h5>
        </div>

    <?php else : ?>

        <section class="container">
            <article>
                <h5>Merci de bien vouloir vous identifier SVP !</h5>
            </article>
        </section>

    <?php endif; ?>
    <!-- Fin du Message qui permet d'afficher le nom et le prénom de l'utilisateur -->

    <!-- INCLURE ICI LE CENTRE DE MA PAGE   -->
    <main class="container">
        <?php include $template ?>
    </main>
    <!-- FIN INCLUSION DU CENTRE DE MA PAGE   -->
    <footer>
        <!--Partie haute-->

        <div class="container">
            <section class="footer__top">
                <a name="contact">
                    <article>
                        <ul>
                            <li>Horraires</li>
                            <li>Lun-Jeu : 10h00 - 19h00</li>
                            <li>Ven : 10h00 - 20h00</li>
                            <li>Sam : 09h00 - 20h00</li>
                            <li>Dim : sur RDV</li>
                        </ul>
                    </article>
                </a>

                <article>
                    <ul>
                        <li>Contact</li>
                        <li>666 Rue Monte au ciel</li>
                        <li>44100 Nantes</li>
                        <li>06 06 06 06 06</li>
                        <li>02 02 02 02 02</li>
                    </ul>
                </article>

                <article>
                    <ul>
                        <li>Réseaux sociaux</li>
                        <li>
                            <a href="https://fr-fr.facebook.com/"><i class="fa-brands fa-facebook-f facebook"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram instagram"></i></a>
                        </li>
                        <li>
                            <a href="https://twitter.com/"><i class="fa-brands fa-twitter twitter"></i></a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com"><i class="fa-brands fa-youtube youtube"></i></a>
                        </li>
                    </ul>
                </article>
            </section>
        </div>

        <!--Partie basse-->
    </footer>
    <script type="text/javascript" src="../public/JS/carousel.js"></script>
    <script type="text/javascript" src="../public/JS/switch.js"></script>
</body>

</html>