<h1>Visualisation d'un bien</h1>

<p>Nom : <?= htmlspecialchars($bien['name']) ?>
</p>
<p>Description : <?= htmlspecialchars($bien['description']) ?>
</p>
<p> Prix : <?= htmlspecialchars($bien['price']) ?>€
</p>
<img src="../public/imagesBDD/<?= htmlspecialchars($bien['image']) ?>" alt="img du bien">
<p>Catégorie : <?= htmlspecialchars($bien['category']) ?>
</p>

<button type="button" class="btn btn-warning"><a href=" index.php?route=accueil">Retour</a></button>