<h1>Visualisation d'un Utilisateur</h1>

<p>Nom : <?= htmlspecialchars($user['nom']) ?>
</p>
<p>Prénom : <?= htmlspecialchars($user['prenom']) ?>
</p>
<p>Login : <?= htmlspecialchars($user['login']) ?>
</p>
<p>Pass : <?= htmlspecialchars($user['pass']) ?>
</p>
<p>Email : <?= htmlspecialchars($user['email']) ?>
</p>

<button type="button" class="btn btn-warning"><a href=" index.php?route=users">Retour</a></button>